# Generated by Django 5.0.2 on 2024-03-03 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_basket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'ordering': ('item',), 'verbose_name': 'корзина', 'verbose_name_plural': 'корзины'},
        ),
    ]
